import{i,S as f}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const m="https://pixabay.com/api",p="46511774-6d45b03e21a284b47c5b7e772";function g(r){const o=new URLSearchParams({key:p,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}),n=`${m}/?${o}`;return fetch(n).then(s=>{if(!s.ok)throw new Error("Failed to fetch images");return s.json()}).then(s=>s.hits)}function y(r){const o=document.querySelector(".gallery"),n=r.map(({webformatURL:s,largeImageURL:e,tags:t,likes:a,views:c,comments:u,downloads:d})=>`
        <li><a href="${e}" class="gallery-item" data-lightbox="image">
            <div class="image-container"><img src="${s}" alt="${t}" loading="lazy" /></div>
            <div class="card-description">
                <p class="info"><span>Likes</span> ${a}</p>
                <p class="info"><span>Views</span> ${c}</p>
                <p class="info"><span>Comments</span> ${u}</p>
                <p class="info"><span>Downloads</span> ${d}</p>
            </div>
        </a></li>
    `).join("");o.innerHTML=`<ul class="gallery-list">${n}</ul>`}function h(){const r=document.getElementById("loader");r.style.display="block"}function L(){const r=document.getElementById("loader");r.style.display="none"}function b(){const r=document.querySelector(".gallery");r.innerHTML=""}const l=document.querySelector(".search-form");l.addEventListener("submit",r=>{r.preventDefault();const o=r.target.elements.query.value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search term!"});return}l.reset(),b(),h(),g(o).then(n=>{n.length===0?i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(y(n),new f(".gallery a").refresh())}).catch(n=>{console.error(n),i.error({title:"Error",message:"Something went wrong. Please try again later."})}).finally(()=>{L()})});
//# sourceMappingURL=index.js.map
